"""Render the immutable shadow snapshot, lineup locks and settlements."""
import argparse,json
from html import escape
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];BASE=ROOT/'outputs/shadow_testing'
def main():
    p=argparse.ArgumentParser();p.add_argument('--weekend',required=True);a=p.parse_args();out=BASE/a.weekend
    snap=json.loads((out/'environment_snapshot.json').read_text(encoding='utf-8'));manifest=json.loads((out/'manifest.json').read_text(encoding='utf-8'));selected=sorted([r for r in snap['fixtures'] if r['selected_environment']],key=lambda r:r['weekend_rank']);locks={p.stem:json.loads(p.read_text(encoding='utf-8')) for p in (out/'lineup_locks').glob('*.json')} if (out/'lineup_locks').exists() else {};settled={p.stem:json.loads(p.read_text(encoding='utf-8')) for p in (out/'settled').glob('*.json')} if (out/'settled').exists() else {};possible_path=out/'latest_possible_lineups.json';possible={r['match_id']:r for r in json.loads(possible_path.read_text(encoding='utf-8'))['forecasts']} if possible_path.exists() else {}
    rows=''
    for r in selected:
        lock=locks.get(r['match_id']);result=settled.get(r['match_id']);status='Settled' if result else 'Picks locked' if lock else 'Awaiting confirmed lineup';picks=(result or lock or {}).get('picks',[])
        picktext='<br>'.join(f"{escape(x['player'])} — {'A+B' if x.get('B') else 'A'}"+(f" — {x.get('shots')} shots — {'HIT' if x.get('hit') else 'MISS' if x.get('hit') is False else 'unknown'}" if result else '') for x in picks) or 'No locked player selection yet'
        forecast=possible.get(r['match_id']);provisional=forecast['provisional_picks'] if forecast else [];prov='<br>'.join(f"{escape(x['player'])} — {'A+B' if x['B'] else 'A'} — {x['avg_shots']:.1f} avg shots" for x in provisional) or 'No provisional possible-XI selection'
        rows+=f'<tr><td>{r["weekend_rank"]}</td><td>{escape(r["fixture"])}</td><td>{r["environment_score"]}</td><td>{r["confidence_tier"]}</td><td>{r["projected_home_shots"]:.1f}</td><td>{status}</td><td>{picktext}</td><td>{prov}</td></tr>'
    html=f'''<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Prospective shadow weekend</title><style>body{{font:16px/1.5 system-ui;max-width:1300px;margin:30px auto;padding:0 18px;background:#f3f6f8;color:#183142}}table{{border-collapse:collapse;background:#fff;width:100%}}th,td{{padding:10px;border-bottom:1px solid #ddd;vertical-align:top;text-align:left}}.scroll{{overflow:auto}}.lock{{background:#e7f5ee;padding:15px;border-left:5px solid #23865d}}.warn{{background:#fff3cf;padding:15px;border-left:5px solid #d99200}}code{{word-break:break-all}}</style><h1>Prospective shadow test — {a.weekend}</h1><p class="lock"><b>Environment snapshot locked before outcomes.</b><br>SHA-256: <code>{manifest['environment_snapshot_sha256']}</code></p><p class="warn"><b>Possible-XI candidates are provisional, not official picks.</b> They use recent starting patterns. A player becomes a recorded selection only after the confirmed starting lineup is captured before kickoff.</p><p>{len(snap['fixtures'])} fixtures scanned · {sum(r['eligible'] for r in snap['fixtures'])} ranked · {len(selected)} selected environments · {len(locks)} lineup locks · {len(settled)} settled matches.</p><div class="scroll"><table><tr><th>Rank</th><th>Fixture</th><th>Score</th><th>Tier</th><th>Projected home shots</th><th>Status</th><th>Confirmed-lineup selections</th><th>Possible-XI provisional selections</th></tr>{rows}</table></div><p><a href="environment_snapshot.json">Immutable environment data</a> · <a href="latest_possible_lineups.json">Latest possible lineups</a> · <a href="manifest.json">Manifest</a></p></html>''';(out/'index.html').write_text(html,encoding='utf-8')
    page=ROOT/'outputs/project_site/dist/index.html'
    if page.exists():
        text=page.read_text(encoding='utf-8');start,end='<!-- SHADOW_TEST_START -->','<!-- SHADOW_TEST_END -->'
        if start in text:before,tail=text.split(start,1);text=before+tail.split(end,1)[1]
        panel=f'''{start}<section id="shadow-test" class="panel" style="margin:24px 0"><div class="eyebrow">LIVE RESEARCH · PROSPECTIVE SHADOW MODE</div><h2>Weekend {a.weekend}: environment snapshot locked</h2><p>{len(snap['fixtures'])} fixtures scanned; {len(selected)} environments selected. Player selections remain empty until confirmed lineups are captured before kickoff.</p><p><a href="../../shadow_testing/{a.weekend}/index.html">Open the live shadow ledger</a></p></section>{end}''';page.write_text(text.replace('</header>','</header>'+panel,1),encoding='utf-8')
    print(json.dumps({'weekend':a.weekend,'selected_environments':len(selected),'lineup_locks':len(locks),'settled':len(settled),'output':str(out/'index.html')},indent=2))
if __name__=='__main__':main()
